# Generated by Django 5.0.7 on 2024-07-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhar', models.IntegerField(max_length=50)),
                ('Created_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_email', models.EmailField(max_length=30)),
                ('Aadhar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.aadhar')),
            ],
        ),
    ]
